spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:reservations}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
  dbcp2:
    max-wait-millis: 30000
    validation-query: select 1
    validation-query-timeout: 30
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
springdoc:
  pathsToMatch: /api/**
service:
  endpoint:
    addresses: http://192.168.86.103:8080/api/addresses
    addressTypes: http://192.168.86.103:8080/api/addresstypes
    states: http://192.168.86.103:8080/api/states
    users: http://192.168.86.103:8080/api/users
    userTypes: http://192.168.86.103:8080/api/usertypes
